

services:
  web:
    build: .
    command: gunicorn syswatch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # persist SQLite db
    ports:
      - "8000:8000"
    env_file:
      - .env
